project:
  type: website
  output-dir: docs

website:
  title: "Prince Agyapong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cardiox_site_reliability.qmd
        text: Site Reliability
